// Mocks generated by Mockito 5.4.6 from annotations
// in dren/test/features/sleep/presentation/bloc/sleep_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dren/core/services/health_service.dart' as _i6;
import 'package:dren/core/services/health_sync_service.dart' as _i5;
import 'package:dren/features/exercise/domain/entities/entities.dart' as _i15;
import 'package:dren/features/sleep/domain/entities/meditation.dart' as _i13;
import 'package:dren/features/sleep/domain/entities/sleep_habit_log.dart'
    as _i3;
import 'package:dren/features/sleep/domain/entities/sleep_schedule.dart' as _i2;
import 'package:dren/features/sleep/domain/entities/sleep_session.dart' as _i9;
import 'package:dren/features/sleep/domain/repositories/sleep_repository.dart'
    as _i4;
import 'package:dren/features/sleep/domain/usecases/get_last_night_sleep.dart'
    as _i7;
import 'package:dren/features/sleep/domain/usecases/get_meditations.dart'
    as _i12;
import 'package:dren/features/sleep/domain/usecases/get_sleep_history.dart'
    as _i14;
import 'package:dren/features/sleep/domain/usecases/get_sleep_schedule.dart'
    as _i10;
import 'package:dren/features/sleep/domain/usecases/log_sleep_habits.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSleepSchedule_0 extends _i1.SmartFake implements _i2.SleepSchedule {
  _FakeSleepSchedule_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSleepHabitLog_1 extends _i1.SmartFake implements _i3.SleepHabitLog {
  _FakeSleepHabitLog_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeeklySleepStats_2 extends _i1.SmartFake
    implements _i4.WeeklySleepStats {
  _FakeWeeklySleepStats_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHealthSyncResult_3 extends _i1.SmartFake
    implements _i5.HealthSyncResult {
  _FakeHealthSyncResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHealthResult_4<T> extends _i1.SmartFake
    implements _i6.HealthResult<T> {
  _FakeHealthResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetLastNightSleep].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLastNightSleep extends _i1.Mock implements _i7.GetLastNightSleep {
  MockGetLastNightSleep() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i9.SleepSession?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<_i9.SleepSession?>.value(),
      ) as _i8.Future<_i9.SleepSession?>);
}

/// A class which mocks [GetSleepSchedule].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSleepSchedule extends _i1.Mock implements _i10.GetSleepSchedule {
  MockGetSleepSchedule() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.SleepSchedule> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8.Future<_i2.SleepSchedule>.value(_FakeSleepSchedule_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i8.Future<_i2.SleepSchedule>);
}

/// A class which mocks [LogSleepHabits].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogSleepHabits extends _i1.Mock implements _i11.LogSleepHabits {
  MockLogSleepHabits() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.SleepHabitLog?> getForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForDate,
          [date],
        ),
        returnValue: _i8.Future<_i3.SleepHabitLog?>.value(),
      ) as _i8.Future<_i3.SleepHabitLog?>);

  @override
  _i8.Future<void> save(_i3.SleepHabitLog? log) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [log],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.SleepHabitLog> toggleHabit({
    required DateTime? date,
    required String? habitName,
    required bool? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleHabit,
          [],
          {
            #date: date,
            #habitName: habitName,
            #value: value,
          },
        ),
        returnValue: _i8.Future<_i3.SleepHabitLog>.value(_FakeSleepHabitLog_1(
          this,
          Invocation.method(
            #toggleHabit,
            [],
            {
              #date: date,
              #habitName: habitName,
              #value: value,
            },
          ),
        )),
      ) as _i8.Future<_i3.SleepHabitLog>);
}

/// A class which mocks [GetMeditations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMeditations extends _i1.Mock implements _i12.GetMeditations {
  MockGetMeditations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i13.Meditation>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i8.Future<List<_i13.Meditation>>.value(<_i13.Meditation>[]),
      ) as _i8.Future<List<_i13.Meditation>>);

  @override
  _i8.Future<List<_i13.Meditation>> byCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #byCategory,
          [category],
        ),
        returnValue:
            _i8.Future<List<_i13.Meditation>>.value(<_i13.Meditation>[]),
      ) as _i8.Future<List<_i13.Meditation>>);

  @override
  _i8.Future<_i13.Meditation?> byId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #byId,
          [id],
        ),
        returnValue: _i8.Future<_i13.Meditation?>.value(),
      ) as _i8.Future<_i13.Meditation?>);
}

/// A class which mocks [GetSleepHistory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSleepHistory extends _i1.Mock implements _i14.GetSleepHistory {
  MockGetSleepHistory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i9.SleepSession>> call({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i8.Future<List<_i9.SleepSession>>.value(<_i9.SleepSession>[]),
      ) as _i8.Future<List<_i9.SleepSession>>);

  @override
  _i8.Future<_i9.SleepSession?> forDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #forDate,
          [date],
        ),
        returnValue: _i8.Future<_i9.SleepSession?>.value(),
      ) as _i8.Future<_i9.SleepSession?>);

  @override
  _i8.Future<_i4.WeeklySleepStats> getWeeklyStats(DateTime? weekStart) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeklyStats,
          [weekStart],
        ),
        returnValue:
            _i8.Future<_i4.WeeklySleepStats>.value(_FakeWeeklySleepStats_2(
          this,
          Invocation.method(
            #getWeeklyStats,
            [weekStart],
          ),
        )),
      ) as _i8.Future<_i4.WeeklySleepStats>);

  @override
  _i8.Future<double> getAverageScore(int? days) => (super.noSuchMethod(
        Invocation.method(
          #getAverageScore,
          [days],
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);
}

/// A class which mocks [HealthSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthSyncService extends _i1.Mock implements _i5.HealthSyncService {
  MockHealthSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> isHealthAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isHealthAvailable,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> hasPermissions() => (super.noSuchMethod(
        Invocation.method(
          #hasPermissions,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i5.HealthSyncResult> syncAll() => (super.noSuchMethod(
        Invocation.method(
          #syncAll,
          [],
        ),
        returnValue:
            _i8.Future<_i5.HealthSyncResult>.value(_FakeHealthSyncResult_3(
          this,
          Invocation.method(
            #syncAll,
            [],
          ),
        )),
      ) as _i8.Future<_i5.HealthSyncResult>);

  @override
  _i8.Future<_i6.HealthResult<_i6.HealthDailySummary>> syncTodayActivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncTodayActivity,
          [],
        ),
        returnValue: _i8.Future<_i6.HealthResult<_i6.HealthDailySummary>>.value(
            _FakeHealthResult_4<_i6.HealthDailySummary>(
          this,
          Invocation.method(
            #syncTodayActivity,
            [],
          ),
        )),
      ) as _i8.Future<_i6.HealthResult<_i6.HealthDailySummary>>);

  @override
  _i8.Future<_i6.HealthResult<_i6.HealthSleepData>> syncSleep() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncSleep,
          [],
        ),
        returnValue: _i8.Future<_i6.HealthResult<_i6.HealthSleepData>>.value(
            _FakeHealthResult_4<_i6.HealthSleepData>(
          this,
          Invocation.method(
            #syncSleep,
            [],
          ),
        )),
      ) as _i8.Future<_i6.HealthResult<_i6.HealthSleepData>>);

  @override
  _i8.Future<_i6.HealthResult<List<_i6.HealthWorkoutData>>> syncWorkouts() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWorkouts,
          [],
        ),
        returnValue:
            _i8.Future<_i6.HealthResult<List<_i6.HealthWorkoutData>>>.value(
                _FakeHealthResult_4<List<_i6.HealthWorkoutData>>(
          this,
          Invocation.method(
            #syncWorkouts,
            [],
          ),
        )),
      ) as _i8.Future<_i6.HealthResult<List<_i6.HealthWorkoutData>>>);

  @override
  _i8.Future<bool> saveWorkout(_i15.WorkoutSession? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWorkout,
          [session],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> saveMeal({
    required DateTime? timestamp,
    required int? calories,
    required double? protein,
    required double? carbs,
    required double? fat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMeal,
          [],
          {
            #timestamp: timestamp,
            #calories: calories,
            #protein: protein,
            #carbs: carbs,
            #fat: fat,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  bool isDuplicateWorkout(
    _i6.HealthWorkoutData? externalWorkout,
    List<_i15.WorkoutSession>? localWorkouts,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicateWorkout,
          [
            externalWorkout,
            localWorkouts,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.HealthWorkoutData> filterDuplicates(
    List<_i6.HealthWorkoutData>? externalWorkouts,
    List<_i15.WorkoutSession>? localWorkouts,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterDuplicates,
          [
            externalWorkouts,
            localWorkouts,
          ],
        ),
        returnValue: <_i6.HealthWorkoutData>[],
      ) as List<_i6.HealthWorkoutData>);

  @override
  _i9.SleepSession? convertToSleepSession(
    _i6.HealthSleepData? healthSleep,
    String? oderId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #convertToSleepSession,
        [
          healthSleep,
          oderId,
        ],
      )) as _i9.SleepSession?);
}
